### ISSUE TITLE
Feature Request: Automatic Import of Postfinance Data

### ISSUE THREAD

**Issue by caillou** [orbiting/backends#490]
# Automatic Import of Postfinance Data

## Current Situation

As of now, the inport if Postfinance Data is a semi-manual task. These are the steps:

- Log in to the E-Finance web platform.
- Download CSV with payment information.
- Download PDF containing images of orange payment slips.
- Log in to Orbiting admin web platform.
- Upload the CSV to the admin web platform.
- Manually match payments that do not contain a HR-ID, either using a user information or the payment slip image.
- Manually send payment reminders.
- Manually deactivate users that are way overdue.

## Feature Request

This feature request aims to reduce the time spent and possiblity of errors when importing payment data as follows:

- Automatically request payment information from Postfinance.
- Automatically match payment information.
- If there are unmatched payments:
  - Inform admin users about unmatched payments (Slack, email, …).
  - Offer a UI to the admin users to efficiently match payments.
- Automatcially send out payment reminders.
- Automatically deactivate users that are way overdue.

### Postfinance FDS / EBICS

Postfinace offers the following options to automatically retrieve payment information:

- EBICS [Factsheet](https://www.postfinance.ch/content/dam/pfch/doc/prod/pay/FS_EBICS_479.08_en.pdf)
- FDS (FTP over SSH) [Manuals](https://www.post.ch/static/Post/IT/FDS/manual.html)

| | Pro | Contra |
| - | - | - | 
| **EBICS** | <ul> <li>International standard.</li> <li>Changing bank should be simple.</li> </ul> | <ul> <li>New-ish standard in Switzerland.</li> <li>Complex implementation, [node library](https://github.com/node-ebics/node-ebics-client) is fairly recent and untested.</li> <li>More overhead with Postfinance to get an account.</li> </ul> |
| **FDS** | <ul> <li>Very simple implementation.</li> <li> Very well tested [node library](https://www.npmjs.com/package/ssh2-sftp-client).</li> <li>Less overhead with Postfinance to activate connection.</li> </ul> |  <ul> <li>Propiretary Postfinance standard.</li> </ul> |

Due to the lesser administrative overhead with Postfinance and the well-tested node library, it would be avisable to take the route of **FDS**. 

### ISO 20020

Both, FDS and EBICS, will return the payment information following an [ISO 20020](https://www.iso20022.org/) standard, namely [`camt.053`](https://www.iso20022.org/standardsrepository/type/camt.053.00-08) with suplementay orang payment slipt images.

This implies that the current code that imports a `CSV` needs to be adapted to import a `camt.053.xml` file.

### Postfinance Test Environment

While Postfinance offers a free [testing environment](https://testplattform.postfinance.ch/corporates/?locale=en), it differs for their production environment insofar as files are delivered as ZIP files, rather than plaintext. It might not actually make a lot of sense to use their environment for development.

## Tasks

- [ ] Rewrite import to accept `camt.053.xml` files.
- [ ] Notify admin users of unmatched payments.
- [ ] Automatically send out overdue notifications upon matching.
- [ ] Automatically deactivate users who are way overdue.
- [ ] Set up a development server for testing and development.
- [ ] Connect and download the files.
- [ ] Convert and save payment slip images.
- [ ] Store `jpeg` files.
- [ ] GrapQL Endpoints:
  - [ ] List of unmatched payments with images.
  - [ ] Matching mutation.
- [ ] Imlement a matching wizard on the admin web platform:
  - Display images for orange payment slips.
  - Offer an inline search for Name and/or Address in order to easily match for the information on the orange payment slip or information in the reference message.
  - The list should idally contain the following fields for matching: `pledge amount`, `name`, `adderss`

### Storing Orange Payment Slip Images

It might make sense to store the orange payment slip images as `base64` encoded blobs in the DB. These are very small, can be deleted upon matching a payment, and could be returned as `base64` images in the GraphQL responses.
